#!/bin/sh

[ -f "$HOME/.profile" ] && . "$HOME/.profile"

export XDG_CURRENT_DESKTOP=dwm

dbus-update-activation-environment --systemd \
    DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP

systemctl --user import-environment \
    DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP

dunst &
picom &
slstatus &
feh --bg-fill ~/Pictures/wallpapers/gnu/hurd00.png
redshift -O 4500 &
/home/$USER/.local/bin/kbdlight
exec dwm
